apiVersion: apps/v1
kind: Deployment

metadata:
  name: fitnessweb
  namespace: fitness

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: fitnessweb

  template:
    metadata:
      labels:
        app: fitnessweb

    spec:
      containers:
        - name: fitnessweb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - sh
            - -c
            - |
              python manage.py migrate
              exec gunicorn gym_project.wsgi:application --bind 0.0.0.0:8000

          ports:
            - containerPort: {{ .Values.containerPort }}

          resources:
{{ toYaml .Values.resources | indent 12 }}